### ISSUE TITLE
token tool not starting

### ISSUE THREAD

**Issue by patrickmohrmann** [RPTools/TokenTool#244]
**Describe the bug**
every time i start the application, about 1 cm loading is done and than everything shuts down

**Expected behavior**
I would like to start/use the tool again

**Screenshots**
![image](https://user-images.githubusercontent.com/76265425/141594218-d1bae7a1-ee6e-4225-9093-a5c30f8a549f.png)

**TokenTool Info**
- Version: 2.2.1
- Install: New,

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

I had that once before, it was possible then to use the *.msi file and reinstall the program. that does **NOT** help this time

**Comment by toniemin** [comment]
I may have the exact same problem. Running from the command line gives me this:

`22:34:01.314 (AppSetup.java:60) [JavaFX-Launcher] INFO  - Overlays installed: 183
22:34:01.341 (TokenTool.java:104) [JavaFX-Launcher] INFO  - Environment: Production
22:34:01.341 (TokenTool.java:108) [JavaFX-Launcher] INFO  - Release: 2.1
22:34:01.342 (TokenTool.java:109) [JavaFX-Launcher] INFO  - OS: Linux
22:34:01.342 (TokenTool.java:110) [JavaFX-Launcher] INFO  - 3D Hardware Available? false
Exception in Application init method
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:473)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:372)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:941)

Caused by: java.lang.RuntimeException: Exception in Application init method
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:968)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:198)
        at java.base/java.lang.Thread.run(Thread.java:844)

Caused by: java.lang.IllegalArgumentException: Image dimensions must be positive (w,h > 0)
        at javafx.graphics/javafx.scene.image.Image.<init>(Image.java:737)
        at javafx.graphics/javafx.scene.image.WritableImage.<init>(WritableImage.java:75)
        at net.rptools.tokentool.util.ImageUtil.processMagenta(ImageUtil.java:363)
        at net.rptools.tokentool.util.ImageUtil.getImage(ImageUtil.java:86)
        at net.rptools.tokentool.util.ImageUtil.getOverlayThumb(ImageUtil.java:61)
        at net.rptools.tokentool.client.TokenTool.cacheOverlays(TokenTool.java:201)
        at net.rptools.tokentool.client.TokenTool.cacheOverlays(TokenTool.java:197)
        at net.rptools.tokentool.client.TokenTool.init(TokenTool.java:115)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:897)
        ... 2 more
Exception running application net.rptools.tokentool.client.TokenTool`

**TokenTool Info**
- Version 2.2.1
- Installed via AUR (package tokentool-bin)

**Desktop**
- OS: Manjaro Linux (Arch-based)
- DE: KDE Plasma

**Comment by toniemin** [comment]
My bad, my problem was a duplicate of issue #218 and I managed to solve it for myself. @patrickmohrmann, do you think you might have the same problem? I fixed the startup issue by converting all the .jpg images to .png images in the TokenTool Cards folder (on Linux in `/home/[username]/.tokentool-rptools/overlays/Cards`. Might be in the Documents folder on Windows?).

**Comment by patrickmohrmann** [comment]
@toniemin thanks for the hint, that didn't solve my problem, but after i removed the whole folder, token-tool started and created a new one. thank you
