### ISSUE TITLE
TokenTool crashes on startup on Ubuntu 21.10

### ISSUE THREAD

**Issue by alec-hoyland** [RPTools/TokenTool#277]
**Describe the bug**

I just installed 2.2.1 on Pop OS 21.10 (an Ubuntu derivative) from the .deb file. Previously (on 21.04 with TokenTool 2.1.x) everything worked perfectly. I can find TokenTool in my list of applications and when I start it I get the "caching overlays" screen and a loading bar, before the application crashes with no error.

**To Reproduce**
1. Run the application from the app launcher.

**Expected behavior**

Token Tool starts up correctly.

**Screenshots**

**TokenTool Info**
- Version: 2.2.1
- Install: Clean install after `sudo apt remove --purge tokentool`.

**Desktop (please complete the following information):**
 - OS: Pop OS 21.10 (Ubuntu derivative)
 - Version 21.10

**More Detailed Desktop Info**
```
OS: Pop!_OS 21.10 x86_64 
Kernel: 5.15.5-76051505-generic 
Uptime: 5 days, 19 hours, 57 mins 
Packages: 2284 (dpkg), 11 (flatpak) 
Shell: zsh 5.8 
Resolution: 3840x2160 
DE: GNOME 40.5 
WM: Mutter 
WM Theme: Pop 
Theme: Pop-dark [GTK2/3] 
Icons: Pop [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD Ryzen 5 3600X (12) @ 3.800GHz 
GPU: AMD ATI Radeon RX 5600 OEM/5600 XT / 5700/5700 XT 
Memory: 8215MiB / 32035MiB 
```

**Java Info**
```
openjdk 11.0.12 2021-07-20
OpenJDK Runtime Environment (build 11.0.12+7-Ubuntu-0ubuntu3)
OpenJDK 64-Bit Server VM (build 11.0.12+7-Ubuntu-0ubuntu3, mixed mode, sharing)
```

**Additional context**
You can also attach files (drag and drop here or paste from clipboard) such as log files or screenshots. For large files, paste a file sharing link.

**Comment by alec-hoyland** [comment]
```
❯ ./TokenTool --help
2021-12-22 11:46:52,197 JavaFX-Launcher ERROR Appenders contains an invalid element or attribute "Sentry"
2021-12-22 11:46:52,207 JavaFX-Launcher ERROR Unable to locate appender "Sentry" for logger config "root"
11:46:52.251 (null:-1) [JavaFX-Launcher] INFO  - Overlays installed: 183
11:46:52.306 (null:-1) [JavaFX-Launcher] INFO  - Environment: Production
11:46:52.306 (null:-1) [JavaFX-Launcher] INFO  - Sentry DSN: https://312e480e6390426095b0a66a11f343a9@sentry.io/1406000
11:46:52.306 (null:-1) [JavaFX-Launcher] INFO  - Vendor: rptools
11:46:52.306 (null:-1) [JavaFX-Launcher] INFO  - Release: 2.2.1
11:46:52.307 (null:-1) [JavaFX-Launcher] INFO  - OS: Linux
11:46:52.307 (null:-1) [JavaFX-Launcher] INFO  - 3D Hardware Available? false
11:46:52.313 (null:-1) [JavaFX-Launcher] DEBUG - caching /home/alec/.tokentool-rptools/overlays
11:46:52.313 (null:-1) [JavaFX-Launcher] DEBUG - caching /home/alec/.tokentool-rptools/overlays/Create
11:46:52.415 (null:-1) [JavaFX-Launcher] DEBUG - caching /home/alec/.tokentool-rptools/overlays/Round
11:46:52.415 (null:-1) [JavaFX-Launcher] DEBUG - caching /home/alec/.tokentool-rptools/overlays/Round/Decorated
11:46:53.041 (null:-1) [JavaFX-Launcher] DEBUG - caching /home/alec/.tokentool-rptools/overlays/Round/Smooth
11:46:54.139 (null:-1) [JavaFX-Launcher] DEBUG - caching /home/alec/.tokentool-rptools/overlays/Round/Gears
11:46:54.209 (null:-1) [JavaFX-Launcher] DEBUG - caching /home/alec/.tokentool-rptools/overlays/Round/Runes
11:46:54.483 (null:-1) [JavaFX-Launcher] DEBUG - caching /home/alec/.tokentool-rptools/overlays/Round/Bottlecaps
11:46:54.791 (null:-1) [JavaFX-Launcher] DEBUG - caching /home/alec/.tokentool-rptools/overlays/Round/Chains
11:46:55.044 (null:-1) [JavaFX-Launcher] DEBUG - caching /home/alec/.tokentool-rptools/overlays/Square
11:46:55.148 (null:-1) [JavaFX-Launcher] DEBUG - caching /home/alec/.tokentool-rptools/overlays/Hex
11:46:55.204 (null:-1) [JavaFX-Launcher] DEBUG - caching /home/alec/.tokentool-rptools/overlays/Cards
Exception in Application init method
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
Caused by: java.lang.RuntimeException: Exception in Application init method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Image dimensions must be positive (w,h > 0)
	at javafx.graphics/javafx.scene.image.Image.<init>(Unknown Source)
	at javafx.graphics/javafx.scene.image.WritableImage.<init>(Unknown Source)
	at net.rptools.tokentool@2.2.1/net.rptools.tokentool.util.ImageUtil.processMagenta(Unknown Source)
	at net.rptools.tokentool@2.2.1/net.rptools.tokentool.util.ImageUtil.getImage(Unknown Source)
	at net.rptools.tokentool@2.2.1/net.rptools.tokentool.util.ImageUtil.getOverlayThumb(Unknown Source)
	at net.rptools.tokentool@2.2.1/net.rptools.tokentool.client.TokenTool.cacheOverlays(Unknown Source)
	at net.rptools.tokentool@2.2.1/net.rptools.tokentool.client.TokenTool.cacheOverlays(Unknown Source)
	at net.rptools.tokentool@2.2.1/net.rptools.tokentool.client.TokenTool.init(Unknown Source)
	... 3 more
Exception running application net.rptools.tokentool.client.TokenTool
```

**Comment by Phergus** [comment]
For some reason the included Cards overlays give some image libraries fits.

You can delete them if you don't want them or you can load them into an editor and then re-save them which may help.

**Comment by trev-dev** [comment]
Just an FYI, the same issue is happening for me in Fedora 35 via the RPM Package. Removing the cards helped.

**Comment by XaverStiensmeier** [comment]
FYI, the same issue is happening for me in Ubuntu22.04. Removing the cards helped.

**Comment by jonititan** [comment]
so for those wondering here is the solution. require imagemagick installed
navigate to the card folder. ~/.tokentool-rptools/overlays/Cards on my install

mogrify -auto-orient -format png *.jpg    

then

rm *.jpg
