### ISSUE TITLE
Crash to desktop on loading

### ISSUE THREAD

**Issue by TheMatthew** [RPTools/TokenTool#331]
**Describe the bug**
Token tool does not launch from a clean install of Ubuntu 22.04

**To Reproduce**
I have a stack trace.
/opt/tokentool/bin$ ./TokenTool 
2022-06-11 14:54:50,178 JavaFX-Launcher ERROR Appenders contains an invalid element or attribute "Sentry"
2022-06-11 14:54:50,190 JavaFX-Launcher ERROR Unable to locate appender "Sentry" for logger config "root"
14:54:50.256 (null:-1) [JavaFX-Launcher] INFO  - Overlays installed: 183
14:54:50.293 (null:-1) [JavaFX-Launcher] INFO  - Environment: Production
14:54:50.294 (null:-1) [JavaFX-Launcher] INFO  - Sentry DSN: https://312e480e6390426095b0a66a11f343a9@sentry.io/1406000
14:54:50.294 (null:-1) [JavaFX-Launcher] INFO  - Vendor: rptools
14:54:50.294 (null:-1) [JavaFX-Launcher] INFO  - Release: 2.2.1
14:54:50.295 (null:-1) [JavaFX-Launcher] INFO  - OS: Linux
14:54:50.295 (null:-1) [JavaFX-Launcher] INFO  - 3D Hardware Available? false
14:54:50.303 (null:-1) [JavaFX-Launcher] DEBUG - caching /home/matthew/.tokentool-rptools/overlays
14:54:50.303 (null:-1) [JavaFX-Launcher] DEBUG - caching /home/matthew/.tokentool-rptools/overlays/Cards
Exception in Application init method
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
Caused by: java.lang.RuntimeException: Exception in Application init method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Image dimensions must be positive (w,h > 0)
	at javafx.graphics/javafx.scene.image.Image.<init>(Unknown Source)
	at javafx.graphics/javafx.scene.image.WritableImage.<init>(Unknown Source)
	at net.rptools.tokentool@2.2.1/net.rptools.tokentool.util.ImageUtil.processMagenta(Unknown Source)
	at net.rptools.tokentool@2.2.1/net.rptools.tokentool.util.ImageUtil.getImage(Unknown Source)
	at net.rptools.tokentool@2.2.1/net.rptools.tokentool.util.ImageUtil.getOverlayThumb(Unknown Source)
	at net.rptools.tokentool@2.2.1/net.rptools.tokentool.client.TokenTool.cacheOverlays(Unknown Source)
	at net.rptools.tokentool@2.2.1/net.rptools.tokentool.client.TokenTool.cacheOverlays(Unknown Source)
	at net.rptools.tokentool@2.2.1/net.rptools.tokentool.client.TokenTool.init(Unknown Source)
	... 3 more
Exception running application net.rptools.tokentool.client.TokenTool

**Expected behavior**
Should load. 

**Screenshots**

**TokenTool Info**
- Version: 2.2.1
- Install: New

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux
 - Version 22.04

**Additional context**
You can also attach files (drag and drop here or paste from clipboard) such as log files or screenshots. For large files, paste a file sharing link.

**Comment by Phergus** [comment]
Delete the card files in: `/home/matthew/.tokentool-rptools/overlays/Cards`

**Comment by TheMatthew** [comment]
Worked!

Was a card corrupt in the installer? I used the deb.

**Comment by Phergus** [comment]
There is something about those JPGs that the image reader libraries used on Linux don't like.  Chances are that just loading/re-saving them out of a different image editor would be sufficient.

**Comment by dpocai** [comment]
I was having the same issue.  Through trial and error I was able to determine jpg files don't want to load for some reason.  Using GIMP, I converted all the jpg images to png. I was then able to launch the program and see the overlays.
